apiVersion: v1
kind: Namespace
metadata:
  name: iperf

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: iperf3-server
  namespace: iperf
spec:
  serviceName: "iperf3-server"
  replicas: 3
  selector:
    matchLabels:
      app: iperf3
  template:
    metadata:
      labels:
        app: iperf3
    spec:
      containers:
      - name: iperf3
        image: networkstatic/iperf3
        args: ["-s"]
        ports:
        - containerPort: 5201


---
apiVersion: v1
kind: Service
metadata:
  name: iperf3-server
  namespace: iperf
spec:
  clusterIP: None
  selector:
    app: iperf3
  ports:
  - port: 5201
    targetPort: 5201

