apiVersion: v1
kind: Namespace
metadata:
  name: iperf

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-server
  namespace: iperf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3
  template:
    metadata:
      labels:
        app: iperf3
    spec:
      containers:
      - name: iperf3
        image: networkstatic/iperf3
        args: ["-s"]  # start in server mode
        ports:
        - containerPort: 5201

---
apiVersion: v1
kind: Service
metadata:
  name: iperf3
  namespace: iperf
spec:
  selector:
    app: iperf3
  ports:
  - port: 5201
    targetPort: 5201
    protocol: TCP
