apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cpu-inference-app
spec:
  project: default
  source:
    repoURL: https://github.com/<your-org>/tf-cpu-inference-k8s.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: inference
  syncPolicy:
    automated: {}
