apiVersion: batch/v1
kind: Job
metadata:
  name: iperf3-client-0
  namespace: iperf
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: iperf3
        image: networkstatic/iperf3
        command: ["iperf3"]
        args: ["-c", "iperf3-server-0.iperf3-server.iperf.svc.cluster.local", "-t", "10"]

---
apiVersion: batch/v1
kind: Job
metadata:
  name: iperf3-client-1
  namespace: iperf
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: iperf3
        image: networkstatic/iperf3
        command: ["iperf3"]
        args: ["-c", "iperf3-server-1.iperf3-server.iperf.svc.cluster.local", "-t", "10"]

---
apiVersion: batch/v1
kind: Job
metadata:
  name: iperf3-client-2
  namespace: iperf
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: iperf3
        image: networkstatic/iperf3
        command: ["iperf3"]
        args: ["-c", "iperf3-server-2.iperf3-server.iperf.svc.cluster.local", "-t", "10"]
